{{ui.modal.close()}}
{{ui.inp_ticket_title.reset()}}
{{ui.slct_createTick_type.reset()}}
{{ui.slct_createTick_importancy.reset()}}
{{ui.slct_createTick_urgency.reset()}}
{{ui.slct_createTick_details.reset()}}
{{ui.slct_createTick_links.reset()}}
{{ui.slct_createTick_sh1.reset()}}
{{ui.slct_createTick_sh2.reset()}}
{{ui.slct_createTick_sh3.reset()}}